# Generated by Django 2.0.6 on 2018-06-23 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_remove_ingredientlistitem_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientlistitem',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
